version: '3.8'

services:
  postgres:
    platform: linux/amd64
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=thesis
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h $1 -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    platform: linux/amd64
    build: ./backend
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    env_file:
      - backend/.env.docker
    command: ["./wait-for.sh", "postgres", "npm", "run", "start"]

  frontend:
    build: ./frontend
    expose:
      - "3000"  # Expose internally for NGINX
    environment:
      NEXT_PUBLIC_SERVER_URL: https://www.travellite-thesis-se4gd.life/api
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Expose NGINX to host machine
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
